#!/bin/bash

# Make the .deb file
rm -rf build
mkdir -p build/DEBIAN
mkdir -p build/usr/local/bin
mkdir -p build/usr/share/mime/packages
mkdir -p build/usr/share/thumbnailers

cp control build/DEBIAN/
cp postinst build/DEBIAN/
cp postrm build/DEBIAN/
chmod 0755 build/DEBIAN/postinst
chmod 0755 build/DEBIAN/postrm

cp src/pesconvert build/usr/local/bin/pesconvert
cp src/PES-Mime.xml build/usr/share/mime/packages/PES-Mime.xml
cp src/PES.thumbnailer build/usr/share/thumbnailers/PES.thumbnailer

dpkg --build build pes-thumbnailer.deb

